name: "Create TODOs"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "joan-yanqiong/todo-to-issue-action@v_jn"
        id: "todo"
